### ISSUE TITLE
Default "quantity" values from FHIR .NET API are funny

### ISSUE THREAD

**Issue by jmandel** [microsoft-healthcare-madison/learning-spike-erp#8]
I'm seeing quantities with .system, .code, and .unit populated in not-obviously-UCUM ways

![image](https://user-images.githubusercontent.com/313089/77611797-47914600-6ef4-11ea-8479-8d2227ff6ef3.png)
per https://ucum.nlm.nih.gov/ucum-lhc/demo.html

Current instance data:
```
                    "measureScore": {
                      "value": 2,
                      "unit": "Number",
                      "system": "http://unitsofmeasure.org",
                      "code": "Number"
                    }
```

**Comment by GinoCanessa** [comment]
Missed closing - fixed a while back.
